### ISSUE TITLE
missing_connection_string error

### ISSUE THREAD

**Issue by envieme** [AnandChowdhary/gpt-search#1]
Not sure what is causing this error:

error node_modules/@vercel/postgres/dist/chunk-HZCE3GDP.js (1:1989) @ d
- error VercelPostgresError: VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found.
    at getSearchResult (./app/search.tsx:44:75)
    at Module.generateMetadata (./app/[[...id]]/page.tsx:14:148)
digest: "2371876043"
null

Server Error
VercelPostgresError: VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found.

app/search.tsx (46:5) @ search

  44 | const found = await sql<{
  45 |   slug: string;
> 46 | }>`SELECT slug FROM SearchResult WHERE query = ${query}`;
     |   ^
  47 | if (found.rows[0]?.slug) return redirect(`/${found.rows[0].slug}`);

**Comment by AnandChowdhary** [comment]
My bad! You should add `POSTGRES_URL` to your environment variables; I missed it because I'm using Vercel which adds this for me. :)

**Comment by envieme** [comment]
Thanks. I am very new to programming and databases. I setup a postgres db and supplied the connection string like this in .env

POSTGRES_URL="username:mypassword@127.0.0.1/gptsearch" where gptsearch is a database i created under username

However, I still get the error which i am unable to solve. 

error Error [VercelPostgresError]: VercelPostgresError - 'invalid_connection_string': This connection string is meant to be used with a direct connection. Make sure to use a pooled connection string or try `createClient()` instead.
